name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build ./base --file ./base/Dockerfile --tag fabiante/steam-cmd:next
    - name: Dockerhub login
      run: $DOCKERHUB_TOKEN | docker login --username fabiante --password-stdin
    - name: Push image
      run: docker push fabiante/steam-cmd:next
